[CmdletBinding()]
param(
    [Parameter(Mandatory)][object]$BenchmarkData,
    [Parameter(Mandatory)][string]$ProjectRoot,
    [string]$OutputPrefix = 'PREVIEW_V2'
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-Value($Object, [string]$Name) { if ($null -eq $Object) { return $null }; $property = $Object.PSObject.Properties[$Name]; if ($null -eq $property) { return $null }; return $property.Value }
function Text($Value) { if ($null -eq $Value -or [string]::IsNullOrWhiteSpace([string]$Value) -or ([string]$Value -match '^(?i:unknown)$')) { return $script:L.not_available }; return [string]$Value }
function Html($Value) { return [System.Net.WebUtility]::HtmlEncode((Text $Value)) }
function Replace-TemplateToken($Template, [string]$Key, $Value) { return $Template.Replace("{{$Key}}", [string]$Value) }
function Number($Value, [string]$Suffix = '') { if ($null -eq $Value) { return $script:L.not_available }; return (([double]$Value).ToString('0.##', [Globalization.CultureInfo]::InvariantCulture) + $Suffix) }
function Serial($Value) { if ($script:ShowSerials) { return Text $Value }; return $script:L.hidden }
function MemoryManufacturer($Value) { $text = Text $Value; if ($text -match '^(0x[0-9A-Fa-f]+|\d+|[0-9A-Za-z]{4})$') { return $script:L.not_available }; return $text }
function DiskBus($Value, $Model = '', [bool]$ForceNvme = $false) { $text = [string]$Value; if ($ForceNvme -or $text -match '(?i)^nvme$' -or ([string]$Model) -match '(?i)\bnvme\b') { return 'NVMe' }; if ($text -match '(?i)^sata$') { return 'SATA' }; return $script:L.not_available }
function DiskType($Media, $Bus, $Model, [bool]$ForceNvme = $false) { if ($ForceNvme -or ([string]$Bus) -match '(?i)^nvme$' -or ([string]$Model) -match '(?i)\bnvme\b') { return $script:L.disk_type_nvme_ssd }; if (([string]$Media) -match '(?i)ssd') { return $script:L.disk_type_ssd }; if (([string]$Media) -match '(?i)fixed hard disk|hdd') { return $script:L.disk_type_hdd }; return $script:L.not_available }
function ShortRunId($Value) { $text = Text $Value; if ($text.Length -gt 8) { return $text.Substring(0,8) + '…' }; return $text }
function Is-VirtualGpu($Gpu) { return (Text (Get-Value $Gpu 'name')) -match 'Virtual|Remote|USB Mobile Monitor|Basic Display|Indirect Display|Mirror|RDP' }
function Primary-Gpu {
    $nvidia = @((Get-Value $BenchmarkData 'nvidia_gpus')) | Select-Object -First 1
    if ($null -ne $nvidia) { return $nvidia }
    $physical = @((Get-Value $BenchmarkData 'gpus') | Where-Object { -not (Is-VirtualGpu $_) }) | Select-Object -First 1
    if ($null -ne $physical) { return $physical }
    return @((Get-Value $BenchmarkData 'gpus')) | Select-Object -First 1
}
function Row([string]$Key, $Value) { "<div class='metric'><span>$(Html $Key)</span><b>$(Html $Value)</b></div>" }
function Card([string]$Title, $Value, [string]$Details) { "<article class='card'><h3>$(Html $Title)</h3><div class='value'>$(Html $Value)</div>$Details</article>" }
function Table([string[]]$Headers, [object[]]$Rows) {
    $head = ($Headers | ForEach-Object { '<th>' + (Html $_) + '</th>' }) -join ''
    $body = foreach ($record in $Rows) { $cells = @($record.Cells); '<tr>' + (($cells | ForEach-Object { '<td>' + (Html $_) + '</td>' }) -join '') + '</tr>' }
    return "<div class='table-wrap'><table><thead><tr>$head</tr></thead><tbody>$($body -join '')</tbody></table></div>"
}
function Diagnostics([object[]]$Warnings, [object[]]$Errors) {
    $items = [Collections.Generic.List[string]]::new()
    if (@($Errors).Count -eq 0) { $items.Add("<div class='notice success'>✓ $($script:L.no_errors)</div>") } else { foreach ($e in @($Errors)) { $items.Add("<div class='notice error'>$(Html $e)</div>") } }
    if (@($Warnings).Count -eq 0) { $items.Add("<div class='notice success'>✓ $($script:L.no_warnings)</div>") } else { foreach ($w in @($Warnings)) { $message = [string]$w; if ($message -match 'Get-PhysicalDisk.*CIM') { $message = 'Информация о накопителях получена резервным методом Windows CIM. На выполнение теста это не повлияло' }; $items.Add("<div class='notice warning'>$(Html $message)</div>") } }
    return $items -join ''
}

$root = [IO.Path]::GetFullPath($ProjectRoot).TrimEnd([IO.Path]::DirectorySeparatorChar)
if (-not (Test-Path -LiteralPath (Join-Path $root '.expc-benchmark-root') -PathType Leaf)) { throw 'Project root marker is missing.' }
$results = Join-Path $root 'results'; $reports = Join-Path $root 'reports'
$templatePath = Join-Path $root 'assets\report-template.html'; $cssPath = Join-Path $root 'assets\report.css'; $localizationPath = Join-Path $root 'assets\report.ru.json'; $configPath = Join-Path $root 'config\benchmark_config.json'
foreach ($path in @($results,$reports,$templatePath,$cssPath,$localizationPath,$configPath)) { if (-not (Test-Path -LiteralPath $path)) { throw "Required resource is missing: $path" } }
$script:L = Get-Content -LiteralPath $localizationPath -Raw -Encoding UTF8 | ConvertFrom-Json
$cfg = Get-Content -LiteralPath $configPath -Raw -Encoding UTF8 | ConvertFrom-Json
$script:ShowSerials = [bool](Get-Value $cfg 'show_serial_numbers')
$computer = Get-Value $BenchmarkData 'computer'; $cpu = Get-Value $BenchmarkData 'cpu'; $memory = Get-Value $BenchmarkData 'memory'; $board = Get-Value $BenchmarkData 'motherboard'; $bios = Get-Value $BenchmarkData 'bios'; $storage = Get-Value (Get-Value $BenchmarkData 'benchmarks') 'storage'; $cpuTest = Get-Value (Get-Value $BenchmarkData 'benchmarks') 'cpu'; $memoryTest = Get-Value (Get-Value $BenchmarkData 'benchmarks') 'memory'; $display = Get-Value $BenchmarkData 'display'; $npu = Get-Value $BenchmarkData 'npu'; $gpuStatus = Get-Value (Get-Value $BenchmarkData 'gpu') 'compute_benchmark_status'
$gpu = Primary-Gpu; $physicalDisks = @((Get-Value $BenchmarkData 'physical_disks')); $logicalDisks = @((Get-Value $BenchmarkData 'logical_disks')); $modules = @((Get-Value $memory 'modules'))
$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'; $runId = Text (Get-Value $BenchmarkData 'run_id'); if ($runId -eq $script:L.not_available) { $runId = [guid]::NewGuid().ToString() }; $safePrefix = $OutputPrefix -replace '[^A-Za-z0-9_-]', '_'
$csvPath = Join-Path $results ("EXPC_Result_{0}_{1}_{2}.csv" -f $safePrefix,$timestamp,$runId)
$htmlPath = Join-Path $reports ("EXPC_Report_{0}_{1}_{2}.html" -f $safePrefix,$timestamp,$runId)

$moduleSummary = (@($modules | ForEach-Object { "$(Text (Get-Value $_ 'device_locator')): $(Number (Get-Value $_ 'capacity_gb') ' GB')" }) -join ' | ')
$systemDisk = Text (Get-Value $storage 'disk_model'); if ($systemDisk -eq $script:L.not_available -and $physicalDisks.Count -gt 0) { $systemDisk = Text (Get-Value $physicalDisks[0] 'model') }
$systemNvme = ((DiskType (Get-Value $storage 'media_type') (Get-Value $storage 'bus_type') $systemDisk) -eq $script:L.disk_type_nvme_ssd -and (DiskBus (Get-Value $storage 'bus_type') $systemDisk) -eq 'NVMe')
$csv = [ordered]@{
    computer_name = Text (Get-Value $computer 'computer_name'); station_label = Text (Get-Value $cfg 'station_label'); benchmark_version = Text (Get-Value $BenchmarkData 'benchmark_version'); run_id = Text (Get-Value $BenchmarkData 'run_id'); status = Text (Get-Value $BenchmarkData 'status'); cpu_name = Text (Get-Value $cpu 'name'); cpu_score = Text (Get-Value $cpuTest 'score'); CPUScoreRaw=(Get-Value $cpuTest 'score'); CPUScoreMillions=(Get-Value $display 'cpu_score_millions'); CPUIndex=(Get-Value $display 'cpu_index'); NPUStatus=(Get-Value $npu 'status'); NPUName=(Get-Value $npu 'name'); NPUExecutionProvider=(Get-Value $npu 'execution_provider'); NPUBenchmarkStatus=(Get-Value $npu 'benchmark_status'); NPUScoreRaw=(Get-Value $npu 'score_raw'); NPUIndex=(Get-Value $npu 'index'); NPULatencyMs=(Get-Value $npu 'latency_ms'); NPUThroughput=(Get-Value $npu 'throughput'); RAMScoreDisplay=(Get-Value $display 'ram_mbps'); StorageWriteDisplay=(Get-Value $display 'storage_write_mbps'); StorageReadDisplay=(Get-Value $display 'storage_read_mbps'); ram_effective_mbps = Text (Get-Value $memoryTest 'effective_mbps'); storage_write_mbps = Text (Get-Value $storage 'sequential_write_mbps'); storage_read_mbps = Text (Get-Value $storage 'sequential_read_mbps'); primary_gpu = Text (Get-Value $gpu 'name'); gpu_driver_version = Text (Get-Value $gpu 'driver_version'); gpu_memory_mb = Text (Get-Value $gpu 'memory_total_mb'); system_disk = $systemDisk; memory_modules = $moduleSummary; motherboard_serial = Serial (Get-Value $board 'serial_number'); bios_serial = Serial (Get-Value $bios 'serial_number'); ram_serials = $script:L.hidden; disk_serials = $script:L.hidden
}
$csvLine = ($csv.Keys | ForEach-Object { '"' + ([string]$csv[$_] -replace '"','""') + '"' }) -join ';'
$csvHeader = ($csv.Keys -join ';')
[IO.File]::WriteAllText($csvPath, "$csvHeader`r`n$csvLine`r`n", [Text.UTF8Encoding]::new($true))
$comparisonPath = Join-Path $reports ("EXPC_Comparison_Full_{0}_{1}_{2}.csv" -f (Text (Get-Value $computer 'computer_name')),$timestamp,$runId)
$systemDiskRecord = @($physicalDisks | Where-Object { (Text (Get-Value $_ 'model')) -eq $systemDisk } | Select-Object -First 1)[0]
$systemDiskSize = Get-Value $systemDiskRecord 'size_gb'
$comparison = [ordered]@{ TestDate=(Get-Value $BenchmarkData 'timestamp'); ComputerName=(Get-Value $computer 'computer_name'); StationName=(Get-Value $cfg 'station_label'); Comment=$null; RunId=(Get-Value $BenchmarkData 'run_id'); BenchmarkVersion=(Get-Value $BenchmarkData 'benchmark_version'); Status=(Get-Value $BenchmarkData 'status'); CPUModel=(Get-Value $cpu 'name'); CPUCores=(Get-Value $cpu 'physical_cores'); CPUThreads=(Get-Value $cpu 'logical_processors'); CPUMaxMHz=(Get-Value $cpu 'max_clock_mhz'); CPUScoreRaw=(Get-Value $cpuTest 'score'); CPUScoreMillions=(Get-Value $display 'cpu_score_millions'); CPUIndex=(Get-Value $display 'cpu_index'); NPUStatus=(Get-Value $npu 'status'); NPUName=(Get-Value $npu 'name'); NPUManufacturer=(Get-Value $npu 'manufacturer'); NPUDriver=(Get-Value $npu 'driver_version'); NPUExecutionProvider=(Get-Value $npu 'execution_provider'); NPUBenchmarkStatus=(Get-Value $npu 'runtime_benchmark_status'); NPUScoreRaw=(Get-Value $npu 'runtime_score_raw'); NPUIndex=(Get-Value $npu 'rated_index'); NPULatencyMs=$null; NPUThroughput=$null; RAMTotalGB=(Get-Value $memory 'total_gb'); RAMModules=$modules.Count; RAMConfiguredMTS=(Get-Value $memory 'configured_speed_mts'); RAMScoreMBs=(Get-Value $display 'ram_mbps'); RAMManufacturer=(@($modules|ForEach-Object{Get-Value $_ 'manufacturer'})-join ' | '); RAMPartNumbers=(@($modules|ForEach-Object{Get-Value $_ 'part_number'})-join ' | '); GPUName=(Get-Value $gpu 'name'); GPUVRAMMB=(Get-Value $gpu 'memory_total_mb'); GPUDriver=(Get-Value $gpu 'driver_version'); GPUTemperatureC=(Get-Value $gpu 'temperature_gpu_c'); GPUPowerLimitW=(Get-Value $gpu 'power_limit_w'); GPUComputeBenchmarkStatus='not_run'; SystemDiskModel=$systemDisk; SystemDiskType=(DiskType (Get-Value $storage 'media_type') (Get-Value $storage 'bus_type') $systemDisk); SystemDiskBus=(DiskBus (Get-Value $storage 'bus_type') $systemDisk); SystemDiskSizeGB=$systemDiskSize; StorageWriteMBs=(Get-Value $display 'storage_write_mbps'); StorageReadMBs=(Get-Value $display 'storage_read_mbps'); Motherboard=(Get-Value $board 'product'); MotherboardManufacturer=(Get-Value $board 'manufacturer'); BIOSVendor=(Get-Value $bios 'manufacturer'); WindowsVersion=(Get-Value $BenchmarkData.operating_system 'version'); WindowsBuild=(Get-Value $BenchmarkData.operating_system 'build_number'); PreflightCPUPercent=(Get-Value $BenchmarkData.preflight 'cpu_load_percent'); WarningsCount=@($BenchmarkData.warnings).Count; ErrorsCount=@($BenchmarkData.errors).Count }
[IO.File]::WriteAllText($comparisonPath, (([pscustomobject]$comparison | ConvertTo-Csv -NoTypeInformation -Delimiter ';') -join "`r`n") + "`r`n", [Text.UTF8Encoding]::new($true))
$compactPath = Join-Path $reports ("EXPC_Comparison_Compact_{0}_{1}_{2}.csv" -f (Text (Get-Value $computer 'computer_name')),$timestamp,$runId)
$npuStatusDisplay = if(-not [bool](Get-Value $npu 'present')){'Отсутствует'}elseif($null -ne (Get-Value $npu 'rated_index')){'Обнаружен'}else{'Обнаружен, рейтинг не определён'}
$compact = [ordered]@{ TestDate=([datetime](Get-Value $BenchmarkData 'timestamp')).ToString('dd.MM.yyyy'); ComputerName=(Text (Get-Value $computer 'computer_name')); StationName=(Text (Get-Value $cfg 'station_label')); Comment=$null; CPUModel=((Text (Get-Value $cpu 'name')) -replace '\(R\)|\(TM\)','' -replace '\s+',' ').Trim(); CPUCoresThreads="$(Get-Value $cpu 'physical_cores') / $(Get-Value $cpu 'logical_processors')"; CPUIndex=[int](Get-Value $display 'cpu_index'); NPUStatus=$npuStatusDisplay; NPURatedTOPS=(Get-Value $npu 'rated_tops'); NPURatedIndex=(Get-Value $npu 'rated_index'); RAMTotalGB=[math]::Round([double](Get-Value $memory 'total_gb')); RAMConfiguredMTS=[int](Get-Value $memory 'configured_speed_mts'); RAMScoreMBs=[int](Get-Value $display 'ram_mbps'); GPUName=(Text (Get-Value $gpu 'name')); GPUVRAMGB=if($null-ne(Get-Value $gpu 'memory_total_mb')){[math]::Round(([double](Get-Value $gpu 'memory_total_mb')/1024),1)}else{$null}; SystemDiskModel=$systemDisk; StorageWriteMBs=[int](Get-Value $display 'storage_write_mbps'); StorageReadMBs=[int](Get-Value $display 'storage_read_mbps'); Motherboard=(Text (Get-Value $board 'product')) }
[IO.File]::WriteAllText($compactPath, (([pscustomobject]$compact | ConvertTo-Csv -NoTypeInformation -Delimiter ';') -join "`r`n") + "`r`n", [Text.UTF8Encoding]::new($true))

$generalCards = (Card $L.processor (Text (Get-Value $cpu 'name')) ((Row 'Ядра' (Text (Get-Value $cpu 'physical_cores'))) + (Row 'Потоки' (Text (Get-Value $cpu 'logical_processors'))))) + (Card $L.graphics (Text (Get-Value $gpu 'name')) ((Row 'Драйвер' (Get-Value $gpu 'driver_version')) + (Row 'Видеопамять' (Number (Get-Value $gpu 'memory_total_mb') ' MB')))) + (Card $L.memory (Number (Get-Value $memory 'total_gb') ' GB') ((Row 'Скорость' (Number (Get-Value $memory 'configured_speed_mts') ' MT/s')) + (Row 'Модулей' $modules.Count))) + (Card $L.storage $systemDisk ((Row 'Шина' (DiskBus (Get-Value $storage 'bus_type') $systemDisk)) + (Row 'Тип' (DiskType (Get-Value $storage 'media_type') (Get-Value $storage 'bus_type') $systemDisk))))
$npuValue = if (-not [bool](Get-Value $npu 'present')) { 'ОТСУТСТВУЕТ' } elseif ($null -ne (Get-Value $npu 'rated_index')) { "NPU RATED INDEX $(Get-Value $npu 'rated_index')" } else { 'ОБНАРУЖЕН' }
$npuDetails = if ($null -ne (Get-Value $npu 'rated_tops')) { (Row 'Паспортный рейтинг' ("$(Get-Value $npu 'rated_tops') TOPS")) } else { (Row 'Паспортный рейтинг' 'не определён') }
$benchmarkCards = (Card 'CPU INDEX' (Text (Get-Value $display 'cpu_index')) (Row 'Raw' ("{0:N2} млн операций" -f [double](Get-Value $display 'cpu_score_millions')))) + (Card 'NPU' $npuValue ((Row 'Устройство' (Get-Value $npu 'name')) + $npuDetails + (Row 'Runtime benchmark' 'не выполнялся'))) + (Card 'RAM' (Number (Get-Value $display 'ram_mbps') ' MB/s') '') + (Card 'STORAGE' (Number (Get-Value $display 'storage_read_mbps') ' MB/s') (Row 'Write' (Number (Get-Value $display 'storage_write_mbps') ' MB/s'))) + (Card 'GRAPHICS' (Text (Get-Value $gpu 'name')) ((Row 'VRAM' (Number (Get-Value $gpu 'memory_total_mb') ' MB')) + (Row 'Compute benchmark' 'не выполнялся')))
$cpuDetails = "<article class='card'><h3>$($L.processor)</h3>" + (Row 'Модель' (Get-Value $cpu 'name')) + (Row 'Производитель' (Get-Value $cpu 'manufacturer')) + (Row 'Макс. частота' (Number (Get-Value $cpu 'max_clock_mhz') ' MHz')) + '</article>'
$memoryRows = foreach ($m in $modules) { [pscustomobject]@{ Cells = @((Get-Value $m 'device_locator'), (Number (Get-Value $m 'capacity_gb') ' GB'), (Number (Get-Value $m 'speed_mts') ' MT/s'), (Number (Get-Value $m 'configured_speed_mts') ' MT/s'), (Get-Value $m 'part_number'), (MemoryManufacturer (Get-Value $m 'manufacturer')), (Get-Value $m 'bank_label')) } }
$memoryDetails = "<article class='card'><h3>$($L.memory)</h3>" + (Table @('Слот','Ёмкость','Скорость','Настроенная','Part number','Производитель','Банк') @($memoryRows)) + '</article>'
$gpuRows = @([pscustomobject]@{ Cells = @((Get-Value $gpu 'name'),(Get-Value $gpu 'driver_version'),(Number (Get-Value $gpu 'memory_total_mb') ' MB'),(Number (Get-Value $gpu 'temperature_gpu_c') ' °C'),(Number (Get-Value $gpu 'power_limit_w') ' W'),(Get-Value $gpu 'pci_bus_id')) })
$gpuDetails = Table @('Модель','Драйвер','VRAM','Температура','Power Limit','PCI') $gpuRows
$boardDetails = "<div class='card'>" + (Row 'Плата' (Get-Value $board 'product')) + (Row 'Производитель' (Get-Value $board 'manufacturer')) + (Row 'Серийный номер' (Serial (Get-Value $board 'serial_number'))) + (Row 'BIOS' (Get-Value $bios 'manufacturer')) + (Row 'BIOS serial' (Serial (Get-Value $bios 'serial_number'))) + '</div>'
$diskRows = foreach ($d in $physicalDisks) { $model = Text (Get-Value $d 'model'); $diskModel = $model; $isSystem = ($model -eq $systemDisk); if ($isSystem) { $model = "$model — $($L.system_disk)" }; [pscustomobject]@{ Cells = @($model,(DiskType (Get-Value $d 'media_type') (Get-Value $d 'bus_type') $diskModel ($isSystem -and $systemNvme)),(DiskBus (Get-Value $d 'bus_type') $diskModel ($isSystem -and $systemNvme)),(Number (Get-Value $d 'size_gb') ' GB'),(Text (Get-Value $d 'health_status')),(Serial (Get-Value $d 'serial_number')) ) } }
$logicalRows = foreach ($d in $logicalDisks) { [pscustomobject]@{ Cells = @((Get-Value $d 'device_id'),(Get-Value $d 'volume_name'),(Number (Get-Value $d 'size_gb') ' GB'),(Number (Get-Value $d 'free_gb') ' GB'),(Number (Get-Value $d 'free_percent') ' %')) } }
$template = Get-Content -LiteralPath $templatePath -Raw -Encoding UTF8; $css = Get-Content -LiteralPath $cssPath -Raw -Encoding UTF8
$statusValue = Text (Get-Value $BenchmarkData 'status')
if ($statusValue.ToLowerInvariant() -eq 'success') { $statusValue = $L.success }
$headerMeta = "<div><b>$($L.label_station)</b><br>$(Html (Text (Get-Value $cfg 'station_label')))</div><div><b>$($L.label_computer)</b><br>$(Html (Get-Value $computer 'computer_name'))</div><div><b>$($L.label_date)</b><br>$(Get-Date -Format 'dd.MM.yyyy HH:mm')</div><div><b>$($L.label_version)</b><br>$(Html (Get-Value $BenchmarkData 'benchmark_version'))</div><div title='$(Html (Get-Value $BenchmarkData 'run_id'))'><b>$($L.label_run_id)</b><br>$(Html (ShortRunId (Get-Value $BenchmarkData 'run_id')))</div><div><b>$($L.label_status)</b><br>$(Html $statusValue)</div>"
$methodology = "<div class='notice'>$(Html $L.method_cpu)<br>$(Html $L.method_ram)<br>$(Html $L.method_storage)<br>$(Html $L.method_compare)<br>$(Html $L.method_note)</div>"
$tokens = @{ INLINE_CSS=$css; REPORT_TITLE=$L.report_title; REPORT_SUBTITLE=$L.report_subtitle; HEADER_META=$headerMeta; GENERAL_CONFIGURATION_TITLE=$L.general_configuration; GENERAL_CARDS=$generalCards; TEST_RESULTS_TITLE=$L.system_ratings; BENCHMARK_CARDS=$benchmarkCards; CPU_DETAILS=$cpuDetails; MEMORY_DETAILS=$memoryDetails; GPU_TITLE=$L.graphics; GPU_DETAILS=$gpuDetails; MOTHERBOARD_BIOS_TITLE=$L.motherboard_bios; MOTHERBOARD_BIOS=$boardDetails; STORAGE_TITLE=$L.storage; PHYSICAL_DISKS=(Table @('Накопитель','Тип','Шина','Размер','Состояние','Серийный номер') @($diskRows)); LOGICAL_DISKS=(Table @('Том','Метка','Размер','Свободно','Свободно %') @($logicalRows)); METHODOLOGY_TITLE=$L.methodology; METHODOLOGY=$methodology; DIAGNOSTICS_TITLE=$L.diagnostics; DIAGNOSTICS=(Diagnostics @($BenchmarkData.warnings) @($BenchmarkData.errors)) }
foreach ($key in $tokens.Keys) { $template = Replace-TemplateToken $template $key $tokens[$key] }
if ($template -match '\{\{[^}]+\}\}') { throw 'Unprocessed HTML placeholder detected.' }
[IO.File]::WriteAllText($htmlPath, $template, [Text.UTF8Encoding]::new($true))
[pscustomobject]@{ csv_path=$csvPath; html_path=$htmlPath; comparison_row_path=$comparisonPath; comparison_compact_path=$compactPath; csv_created=$true; html_created=$true; completed=$true; primary_gpu=(Text (Get-Value $gpu 'name')); warnings=@('XLSX library is not included in the portable package; UTF-8 BOM comparison CSV fallback was created.'); errors=@() }
