[CmdletBinding()]
param([Parameter(Mandatory)]$Benchmark,[Parameter(Mandatory)][string]$ProjectRoot,[Parameter(Mandatory)][string]$JsonPath,[string]$RunId)
Set-StrictMode -Version Latest
$warnings=[Collections.Generic.List[string]]::new();$errors=[Collections.Generic.List[string]]::new();$csvPath=$null;$htmlPath=$null
function P($o,[string]$n){if($null-eq$o){return $null};$q=$o.PSObject.Properties[$n];if($null-eq$q){return $null};$q.Value}
function S($v){if($null-eq$v){return ''};[string]$v}
function I($v){if($null-eq$v){return ''};try{([double]$v).ToString([Globalization.CultureInfo]::InvariantCulture)}catch{S $v}}
function HtmlE($v){[Net.WebUtility]::HtmlEncode((S $v))}
function L($v){return ,([object[]]@($v))}
function M($n,$v){"<div class='metric'><span>$(HtmlE $n)</span><b>$(HtmlE $v)</b></div>"}
function C($n,$v,$d){"<article class='card'><h3>$(HtmlE $n)</h3><div class='value'>$(HtmlE $v)</div>$d</article>"}
function TB($heads,$rows){$h=($heads|ForEach-Object{"<th>$(HtmlE $_)</th>"})-join'';$r=($rows|ForEach-Object{"<tr>"+(($_|ForEach-Object{"<td>$(HtmlE $_)</td>"})-join'')+'</tr>'})-join'';if(!$r){$r="<tr><td colspan='$($heads.Count)' class='muted'>No data available.</td></tr>"};"<div class='table-wrap'><table><thead><tr>$h</tr></thead><tbody>$r</tbody></table></div>"}
try{
 $marker=Join-Path $ProjectRoot '.expc-benchmark-root';$results=Join-Path $ProjectRoot 'results';$reports=Join-Path $ProjectRoot 'reports';$cssFile=Join-Path $ProjectRoot 'assets\report.css';foreach($x in @($marker,$results,$reports,$cssFile,$JsonPath)){if(!(Test-Path -LiteralPath $x)){throw "Required report input is missing: $x"}}
 if(!$RunId){$RunId=S(P $Benchmark 'run_id')};$computer=S(P(P $Benchmark 'computer') 'computer_name');if(!$computer){$computer='UNKNOWN'};$safe=$computer-replace'[^A-Za-z0-9_-]','_';$tag=Get-Date -Format 'yyyyMMdd_HHmmss';$csvPath=Join-Path $results "EXPC_Result_${safe}_${tag}_${RunId}.csv";$htmlPath=Join-Path $reports "EXPC_Report_${safe}_${tag}_${RunId}.html"
 $sys=P $Benchmark 'computer';$os=P $Benchmark 'operating_system';$cpu=P $Benchmark 'cpu';$mem=P $Benchmark 'memory';$mb=P $Benchmark 'motherboard';$bios=P $Benchmark 'bios';$bench=P $Benchmark 'benchmarks';$cb=P $bench 'cpu';$rb=P $bench 'memory';$sb=P $bench 'storage';$gpu=L(P $Benchmark 'gpus');$nv=L(P $Benchmark 'nvidia_gpus');$nv1=$nv|Select-Object -First 1;$pd=L(P $Benchmark 'physical_disks');$mods=L(P $mem 'modules')
 $moduleSummary=($mods|ForEach-Object{"$(S(P $_ 'manufacturer')) $(S(P $_ 'part_number')) $(I(P $_ 'capacity_gb')) GB"})-join' | ';$diskSummary=($pd|ForEach-Object{"$(S(P $_ 'model')) $(I(P $_ 'size_gb')) GB"})-join' | ';$g1=$gpu|Select-Object -First 1
 $row=[ordered]@{schema_version=S(P $Benchmark 'schema_version');benchmark_version=S(P $Benchmark 'benchmark_version');run_id=S(P $Benchmark 'run_id');timestamp=S(P $Benchmark 'timestamp');status=S(P $Benchmark 'status');computer_name=$computer;computer_manufacturer=S(P $sys 'manufacturer');computer_model=S(P $sys 'model');windows_caption=S(P $os 'caption');windows_version=S(P $os 'version');windows_build=S(P $os 'build_number');windows_architecture=S(P $os 'architecture');last_boot_time=S(P $os 'last_boot_time');uptime_seconds=I(P $os 'uptime_seconds');cpu_manufacturer=S(P $cpu 'manufacturer');cpu_name=S(P $cpu 'name');cpu_socket=S(P $cpu 'socket');cpu_physical_cores=I(P $cpu 'physical_cores');cpu_logical_processors=I(P $cpu 'logical_processors');cpu_max_clock_mhz=I(P $cpu 'max_clock_mhz');cpu_l3_cache_kb=I(P $cpu 'l3_cache_kb');motherboard_manufacturer=S(P $mb 'manufacturer');motherboard_product=S(P $mb 'product');motherboard_version=S(P $mb 'version');bios_manufacturer=S(P $bios 'manufacturer');bios_version=S(P $bios 'smbios_version');bios_release_date=S(P $bios 'release_date');boot_mode=S(P $bios 'boot_mode');memory_total_gb=I(P $mem 'total_gb');memory_configured_speed_mts=I(P $mem 'configured_speed_mts');memory_module_count=$mods.Count;memory_modules_summary=$moduleSummary;gpu_count=$gpu.Count;gpu_primary_name=S(P $g1 'name');gpu_primary_driver=S(P $g1 'driver_version');nvidia_gpu_name=S(P $nv1 'name');nvidia_driver_version=S(P $nv1 'driver_version');nvidia_vram_mb=I(P $nv1 'memory_total_mb');nvidia_temperature_c=I(P $nv1 'temperature_gpu_c');nvidia_power_limit_w=I(P $nv1 'power_limit_w');physical_disk_count=$pd.Count;physical_disks_summary=$diskSummary;storage_test_drive=S(P $sb 'drive');storage_test_disk_model=S(P $sb 'disk_model');storage_test_bus_type=S(P $sb 'bus_type');power_plan_name=S(P(P $Benchmark 'power_plan') 'name');cpu_test_completed=S(P $cb 'completed');cpu_threads_used=I(P $cb 'logical_threads_used');cpu_duration_seconds=I(P $cb 'duration_seconds');cpu_total_iterations=I(P $cb 'total_iterations');cpu_operations_per_second=I(P $cb 'operations_per_second');cpu_score=I(P $cb 'score');memory_test_completed=S(P $rb 'completed');memory_test_size_mb=I(P $rb 'test_size_mb');memory_write_mbps=I(P $rb 'write_mbps');memory_copy_mbps=I(P $rb 'copy_mbps');memory_read_mbps=I(P $rb 'read_mbps');memory_effective_mbps=I(P $rb 'effective_mbps');memory_checksum_valid=S(P $rb 'checksum_valid');storage_test_completed=S(P $sb 'completed');storage_test_size_mb=I(P $sb 'test_size_mb');storage_write_mbps=I(P $sb 'sequential_write_mbps');storage_read_mbps=I(P $sb 'sequential_read_mbps');storage_checksum_valid=S(P $sb 'checksum_valid');storage_test_file_deleted=S(P $sb 'test_file_deleted');warnings_count=(L(P $Benchmark 'warnings')).Count;errors_count=(L(P $Benchmark 'errors')).Count;warnings_summary=(L(P $Benchmark 'warnings'))-join' | ';errors_summary=(L(P $Benchmark 'errors'))-join' | '}
 [IO.File]::WriteAllText($csvPath,((([pscustomobject]$row|ConvertTo-Csv -NoTypeInformation -Delimiter ';')-join"`r`n")+"`r`n"),[Text.UTF8Encoding]::new($true));if(@(Import-Csv -LiteralPath $csvPath -Delimiter ';').Count-ne 1){throw 'CSV validation failed.'}
 $modRows=@($mods|ForEach-Object{@(S(P $_ 'manufacturer'),S(P $_ 'part_number'),"$(I(P $_ 'capacity_gb')) GB",S(P $_ 'speed_mts'),S(P $_ 'configured_speed_mts'),S(P $_ 'bank_label'),S(P $_ 'device_locator'))});$gpuRows=@($gpu|ForEach-Object{@(S(P $_ 'name'),S(P $_ 'driver_version'),S(P $_ 'driver_date'),S(P $_ 'video_processor'),S(P $_ 'adapter_ram_bytes'))});$nvRows=@($nv|ForEach-Object{@(S(P $_ 'name'),S(P $_ 'memory_total_mb'),S(P $_ 'driver_version'),S(P $_ 'temperature_gpu_c'),S(P $_ 'power_limit_w'),S(P $_ 'pci_bus_id'))});$pdRows=@($pd|ForEach-Object{@(S(P $_ 'model'),S(P $_ 'serial_number'),S(P $_ 'media_type'),S(P $_ 'bus_type'),"$(I(P $_ 'size_gb')) GB",S(P $_ 'health_status'),S(P $_ 'firmware_version'))});$ldRows=@(L(P $Benchmark 'logical_disks')|ForEach-Object{@(S(P $_ 'device_id'),S(P $_ 'file_system'),"$(I(P $_ 'size_gb')) GB","$(I(P $_ 'free_gb')) GB","$(I(P $_ 'free_percent'))%")});$warningsHtml=if((L(P $Benchmark 'warnings')).Count){((L(P $Benchmark 'warnings')|ForEach-Object{"<div class='notice warning'>$(HtmlE $_)</div>"})-join'')}else{"<div class='notice success'>No warnings detected.</div>"};$errorsHtml=if((L(P $Benchmark 'errors')).Count){((L(P $Benchmark 'errors')|ForEach-Object{"<div class='notice error'>$(HtmlE $_)</div>"})-join'')}else{"<div class='notice success'>No errors detected.</div>"}
 $css=[IO.File]::ReadAllText($cssFile,[Text.UTF8Encoding]::new($false));$summary=(C 'CPU' (P $cpu 'name') '')+(C 'GPU' (($gpu|ForEach-Object{S(P $_ 'name')})-join'; ') '')+(C 'RAM' "$(I(P $mem 'total_gb')) GB" (M 'Configured speed' "$(I(P $mem 'configured_speed_mts')) MT/s"))+(C 'Motherboard' "$(S(P $mb 'manufacturer')) $(S(P $mb 'product'))" '')+(C 'Test Storage' (P $sb 'disk_model') (M 'Drive' (P $sb 'drive')))+(C 'Windows' (P $os 'caption') (M 'Version' (P $os 'version')));$performance=(C 'CPU PERFORMANCE' "Score $(I(P $cb 'score'))" ((M 'Operations/sec' (P $cb 'operations_per_second'))+(M 'Threads' (P $cb 'logical_threads_used'))+(M 'Duration' "$(I(P $cb 'duration_seconds')) s")))+(C 'MEMORY PERFORMANCE' "$(I(P $rb 'effective_mbps')) MB/s" ((M 'Write' "$(I(P $rb 'write_mbps')) MB/s")+(M 'Copy' "$(I(P $rb 'copy_mbps')) MB/s")+(M 'Read' "$(I(P $rb 'read_mbps')) MB/s")+(M 'Test size' "$(I(P $rb 'test_size_mb')) MB")))+(C 'STORAGE PERFORMANCE' "Write $(I(P $sb 'sequential_write_mbps')) MB/s" ((M 'Read' "$(I(P $sb 'sequential_read_mbps')) MB/s")+(M 'Test size' "$(I(P $sb 'test_size_mb')) MB")+(M 'Drive' (P $sb 'drive'))+(M 'Disk model' (P $sb 'disk_model'))))
 $html="<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>EXPC Workstation Benchmark Report</title><style>$css</style></head><body><main class='wrap'><header class='hero'><div><div class='brand'>EXPC<br>AI BENCHMARK PORTABLE</div><h1>EXPC WORKSTATION BENCHMARK REPORT</h1><div class='sub'>Portable System Performance Analysis</div></div><div class='meta'><span class='badge $(HtmlE(P $Benchmark 'status'))'>$(HtmlE(P $Benchmark 'status'))</span><br>$(HtmlE $computer)<br>$(HtmlE(P $Benchmark 'timestamp'))<br>Run ID: $(HtmlE(P $Benchmark 'run_id'))</div></header><h2>GENERAL SUMMARY</h2><section class='grid'>$summary</section><h2>CORE RESULTS</h2><section class='grid performance'>$performance</section><h2>CPU DETAILS</h2><section class='grid'>$(C 'CPU' (P $cpu 'name') ((M 'Manufacturer' (P $cpu 'manufacturer'))+(M 'Socket' (P $cpu 'socket'))+(M 'Physical cores' (P $cpu 'physical_cores'))+(M 'Logical processors' (P $cpu 'logical_processors'))+(M 'Max clock MHz' (P $cpu 'max_clock_mhz'))+(M 'L3 cache KB' (P $cpu 'l3_cache_kb'))))</section><h2>MEMORY DETAILS</h2>$(TB @('Manufacturer','Part Number','Capacity','Speed','Configured Speed','Bank','Device Locator') $modRows)<h2>GPU DETAILS</h2>$(TB @('Name','Driver','Driver Date','Video Processor','Adapter RAM bytes') $gpuRows)<h3>NVIDIA</h3>$(TB @('GPU name','VRAM MB','Driver','Temperature C','Power limit W','PCI bus') $nvRows)<h2>MOTHERBOARD AND BIOS</h2><section class='grid'>$(C 'Motherboard' "$(S(P $mb 'manufacturer')) $(S(P $mb 'product'))" ((M 'Version' (P $mb 'version'))+(M 'Serial' (P $mb 'serial_number'))))$(C 'BIOS' (P $bios 'manufacturer') ((M 'Version' (P $bios 'smbios_version'))+(M 'Release date' (P $bios 'release_date'))+(M 'Boot mode' (P $bios 'boot_mode'))))</section><h2>STORAGE DETAILS</h2>$(TB @('Model','Serial','Media Type','Bus Type','Capacity','Health','Firmware') $pdRows)<br>$(TB @('Drive','File System','Capacity','Free Space','Free Percent') $ldRows)<h2>BENCHMARK METHODOLOGY</h2><div class='notice'>CPU Score is an internal EXPC comparative indicator, not a universal performance score. RAM uses sequential operations. Storage is measured only inside the project folder. Compare results from the same benchmark version; temperature, background processes, power mode, and disk condition can affect results.</div><h2>WARNINGS AND ERRORS</h2>$warningsHtml$errorsHtml<footer class='footer'>EXPC AI Benchmark Portable · Benchmark version $(HtmlE(P $Benchmark 'benchmark_version')) · Schema version $(HtmlE(P $Benchmark 'schema_version')) · $(HtmlE(P $Benchmark 'timestamp'))<br>Results are intended for comparative workstation analysis using the same EXPC benchmark version.</footer></main></body></html>"
 [IO.File]::WriteAllText($htmlPath,$html,[Text.UTF8Encoding]::new($false));$test=[IO.File]::ReadAllText($htmlPath,[Text.UTF8Encoding]::new($false));if(!$test -or $test-notmatch'<!DOCTYPE html>' -or $test-notmatch'EXPC WORKSTATION BENCHMARK REPORT' -or $test-notmatch'<style>' -or $test-match'https?://'){throw 'HTML autonomous validation failed.'};[pscustomobject]@{csv_path=$csvPath;html_path=$htmlPath;csv_created=(Test-Path -LiteralPath $csvPath);html_created=(Test-Path -LiteralPath $htmlPath);completed=$true;warnings=@($warnings);errors=@($errors)}
}catch{$errors.Add($_.Exception.Message);[pscustomobject]@{csv_path=$csvPath;html_path=$htmlPath;csv_created=($null-ne$csvPath-and(Test-Path -LiteralPath $csvPath));html_created=($null-ne$htmlPath-and(Test-Path -LiteralPath $htmlPath));completed=$false;warnings=@($warnings);errors=@($errors)}}
