[CmdletBinding()]
param([string]$CpuName,[string]$CatalogPath)
Set-StrictMode -Version Latest
$warnings=[Collections.Generic.List[string]]::new();$errors=[Collections.Generic.List[string]]::new();$patterns='Neural processors|Neural Processing Unit|\bNPU\b|Intel AI Boost|AMD IPU Device|AMD Ryzen AI|Qualcomm Hexagon|Qualcomm NPU';$found=@()
try { if(Get-Command Get-PnpDevice -ErrorAction SilentlyContinue){$found+=@(Get-PnpDevice -ErrorAction Stop|Where-Object{"$($_.FriendlyName) $($_.Class) $($_.Manufacturer)" -match $patterns}|ForEach-Object{[pscustomobject]@{name=$_.FriendlyName;manufacturer=$_.Manufacturer;device_id=$_.InstanceId;status=$_.Status;method='Get-PnpDevice'}}) } }catch{$warnings.Add("Get-PnpDevice: $($_.Exception.Message)")}
try {$found+=@(Get-CimInstance Win32_PnPEntity -ErrorAction Stop|Where-Object{"$($_.Name) $($_.PNPClass) $($_.Manufacturer)" -match $patterns}|ForEach-Object{[pscustomobject]@{name=$_.Name;manufacturer=$_.Manufacturer;device_id=$_.DeviceID;status=$_.Status;method='Win32_PnPEntity'}})}catch{$warnings.Add("Win32_PnPEntity: $($_.Exception.Message)")}
$device=$found|Select-Object -First 1;if($null-eq$device){return [pscustomobject]@{present=$false;status='absent';name=$null;manufacturer=$null;driver_version=$null;device_id=$null;architecture=$null;rated_tops=$null;rated_index=$null;rating_source=$null;rating_confidence=$null;runtime_benchmark_status='not_implemented';runtime_score_raw=$null;runtime_index=$null;execution_provider=$null;errors=@($errors);warnings=@($warnings)}}
$driver=$null;try{$driver=Get-CimInstance Win32_PnPSignedDriver -ErrorAction Stop|Where-Object{$_.DeviceID-eq$device.device_id}|Select-Object -First 1}catch{$warnings.Add("Win32_PnPSignedDriver: $($_.Exception.Message)")};$entry=$null;try{$entry=(Get-Content $CatalogPath -Raw -Encoding UTF8|ConvertFrom-Json|Where-Object{($CpuName -and (@($_.cpu_patterns)|Where-Object{$CpuName-like"*$_*"})) -and (@($_.npu_patterns)|Where-Object{$device.name-like"*$_*"})}|Select-Object -First 1)}catch{$warnings.Add("NPU catalog: $($_.Exception.Message)")};$rated=if($entry){[double]$entry.rated_tops}else{$null}
[pscustomobject]@{present=$true;status=if($entry){'rated'}else{'detected'};name=$device.name;manufacturer=if($device.manufacturer){$device.manufacturer}else{if($entry){$entry.vendor}else{$null}};driver_version=if($driver){$driver.DriverVersion}else{$null};device_id=$device.device_id;architecture=if($entry){$entry.architecture}else{$null};rated_tops=$rated;rated_index=if($null-ne$rated){[math]::Round($rated*10)}else{$null};rating_source=if($entry){$entry.source_note}else{$null};rating_confidence=if($entry){$entry.confidence}else{$null};runtime_benchmark_status='not_implemented';runtime_score_raw=$null;runtime_index=$null;execution_provider=$null;errors=@($errors);warnings=@($warnings)}
